apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
    ### Create a name for your PVC ###
    name: esa-pvc
    ### Use a namespace that matched your intended consuming pod, or "default" ###
    namespace: default
spec: 
    accessModes: 
        - ReadWriteMany 
    resources: 
        requests: 
            storage: 10Gi 
    storageClassName: unbacked-sc