# Starter pipeline
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure Arc Jumpstart Develop(98a19988-5c3d-4824-a685-f5cf12ae5c19)'
    KeyVaultName: 'ADOPipelineKV'
    SecretsFilter: 'TestCI'
    RunAsPreJob: false

trigger:
- canary

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: 'echo TestCI -> $(TestCI)'
