name: Bug Report
description: File a bug report or an issue
title: "[Bug / Issue]: "
labels: ["Bug-Issue", "Needs-Triage"]
projects: [""]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!

        If your bug report is related to documentation, we kindly ask you to open an issue in our [documentation repository](https://github.com/Azure/arc_jumpstart_docs).

        The intent of this "Bug report" template is to address issues related to Jumpstart Drops. The Arc Jumpstart team does not handle and/or support Azure Arc upstream core product related issues, bugs and feature requests and will try to assist on a best effort basis. For a core product issue or feature request/feedback, please create an official [Azure support ticket](https://azure.microsoft.com/support/create-ticket/) or [general feedback request](https://feedback.azure.com).
  - type: checkboxes
    id: solution
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - label: Issue with a Drop I contributed
        - label: Issue with a Drop I am using
        - label: Issue with the Jumpstart Drops website experience (e.g. broken links, typos)
        - label: I am not sure
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen and how to reproduce?
      placeholder: Tell us what you see! If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: input
    id: solution-url
    attributes:
      label: We need a URL
      description: Share with us the URL to the Drop or where you see and issue happening.
      placeholder: ex. https://jumpstart.azure.com/azure_jumpstart_drops?drop=Deploy%20the%20Azure%20Monitor%20Agent%20to%20a%20Windows%20Azure%20Arc-enabled%20Server&fs=true
    validations:
      required: true    
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output.
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. Make sure to NOT INCLUDE any sensitive information or passwords.
      render: shell      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct and Licensing
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Azure/arc_jumpstart_docs/blob/main/CODE_OF_CONDUCT.md) and the project's [MIT license](https://github.com/microsoft/azure_arc/blob/main/LICENSE-CODE). 
      options:
        - label: I agree to follow this project's Code of Conduct and Licensing terms.
          required: true
