name: Drop last modification validator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * 1"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 20.9.0
        
    - name: Run script to check LastModified
      run: node ./.github/date-validator/validator.js